name: Run E2E tests per DB
description: Run E2E tests per DB

inputs:
  db:
    required: true
    description: db name

runs:
  using: composite
  steps:
    - id: run-tests-per-db
      shell: bash
      run: echo "bla"
