image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addBadge: true

ports:
  - port: 3000
    description: lupa web ui port

  - port: 6006
    description: lupa storybook port

tasks:
  - init: pre-commit install
  - init: go mod download

  - name: Dev Server
    before: cd web
    init: yarn
    command: yarn start

vscode:
  extensions:
    - golang.Go
    - eamodio.gitlens
    - ms-python.python
    - esbenp.prettier-vscode
    - ms-vscode.makefile-tools
    - EditorConfig.EditorConfig
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-azuretools.vscode-docker
