project_name: teletrace
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    main: ./cmd/all-in-one/main.go
    binary: teletrace
    id: teletrace

dockers:
  - image_templates:
      - "teletrace/teletrace:{{ .Tag }}-amd64"
      - "teletrace/teletrace:v{{ .Major }}-amd64"
      - "teletrace/teletrace:v{{ .Major }}.{{ .Minor }}-amd64"
      - "teletrace/teletrace:latest-amd64"
    dockerfile: ./cmd/all-in-one/Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --build-arg=BUILD_INFO={{ .Summary }}
    goarch: amd64
    goos: linux
    extra_files:
      - "go.mod"
      - "go.sum"
      - "cmd"
      - "teletrace-otelcol"
      - "model"
      - "web"
      - "pkg"
      - "plugin"
  - image_templates:
      - "teletrace/teletrace:{{ .Tag }}-arm64v8"
      - "teletrace/teletrace:v{{ .Major }}-arm64v8"
      - "teletrace/teletrace:v{{ .Major }}.{{ .Minor }}-arm64v8"
      - "teletrace/teletrace:latest-arm64v8"
    dockerfile: ./cmd/all-in-one/Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --build-arg=BUILD_INFO={{ .Summary }}
    goarch: arm64
    goos: linux
    extra_files:
      - "go.mod"
      - "go.sum"
      - "cmd"
      - "teletrace-otelcol"
      - "model"
      - "web"
      - "pkg"
      - "plugin"
  - image_templates:
      - "teletrace/teletrace:{{ .Tag }}-armv7"
      - "teletrace/teletrace:v{{ .Major }}-armv7"
      - "teletrace/teletrace:v{{ .Major }}.{{ .Minor }}-armv7"
      - "teletrace/teletrace:latest-armv7"
    dockerfile: ./cmd/all-in-one/Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v7
      - --build-arg=BUILD_INFO={{ .Summary }}
    goarch: arm
    goarm: 7
    goos: linux
    extra_files:
      - "go.mod"
      - "go.sum"
      - "cmd"
      - "teletrace-otelcol"
      - "model"
      - "web"
      - "pkg"
      - "plugin"

docker_manifests:
  - name_template: "teletrace/teletrace:{{ .Tag }}"
    image_templates:
      - "teletrace/teletrace:{{ .Tag }}-amd64"
      - "teletrace/teletrace:{{ .Tag }}-arm64v8"
      - "teletrace/teletrace:{{ .Tag }}-armv7"
  - name_template: "teletrace/teletrace:v{{ .Major }}"
    image_templates:
      - "teletrace/teletrace:v{{ .Major }}-amd64"
      - "teletrace/teletrace:v{{ .Major }}-arm64v8"
      - "teletrace/teletrace:v{{ .Major }}-armv7"
  - name_template: "teletrace/teletrace:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "teletrace/teletrace:v{{ .Major }}.{{ .Minor }}-amd64"
      - "teletrace/teletrace:v{{ .Major }}.{{ .Minor }}-arm64v8"
      - "teletrace/teletrace:v{{ .Major }}.{{ .Minor }}-armv7"
  - name_template: "teletrace/teletrace:latest"
    image_templates:
      - "teletrace/teletrace:latest-amd64"
      - "teletrace/teletrace:latest-arm64v8"
      - "teletrace/teletrace:latest-armv7"

archives:
  - replacements:
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
