receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  sqlite:
    path: "embedded_spans.db"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [sqlite]
