receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  postgres:
    host: http://localhost
    port: 5432
    username: postgres
    password: postgres
    dbname: spans


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [postgresql]
