export const styles = {
  mainContainer: {
    // boxSizing: "border-box",
    // display: "flex",
    // flexDirection: "column",
    // justifyContent: "flex-start",
    // alignItems: "flex-start",
    padding: "7px 16px 7px 30px",
    // gap: "12px",
    background: "#0B0B0D",
    borderLeft: "1px solid #EF5854",
    maxHeight: "240px",
  },
  typography: {
    margin: "0",
    color: "#EF5854",
    fontFamily: "Roboto Mono",
    fontWeight: "400",
    lineHeight: "22px",
    textAlign: "left",
    maxWidth: "500px",
    maxHeight: "50px",
  },
  readMoreSeparationLine: {
    backgroundColor: "#6E6F75",
    width: "107px",
    height: "1px",
    marginLeft: "219.5px",
    marginTop: "3.5px",
  },
  readMoreButton: {
    borderTop: "1px solid #6E6F75",
    width: "107px",
    fontWeight: "500",
    // textAlign: "center",
    fontSize: "10px",
    marginLeft: "236.5px",
    lineHeight: '12px',
    letterSpacing: '1.5px',
    color: "#FFFFFF",
    // marginTop: "2px",
  },
  readMoreText: {
    fontWeight: "500",
    textAlign: "center",
    fontSize: "14px",
    color: "#FFFFFF",
  },
};
