export * from '@mui/icons-material'
export { SvgIcon } from '@mui/material'
export * from './icons/AWSLambdaFunctionIcon'
export * from './icons/CapIcon'
export * from './icons/Custom'
export * from './icons/DynamoDB'
export * from './icons/FSOIcon'
export * from './icons/FSOIconBW'
export * from './icons/Github'
export * from './icons/Google'
export * from './icons/Grpc'
export * from './icons/Http'
export * from './icons/Lambda'
export * from './icons/MongoDB'
export * from './icons/NodeJSIcon'
export * from './icons/Python'
export * from './icons/RabbitMQ'
export * from './icons/Redis'
export * from './icons/Sns'
export * from './icons/Sqs'
export { IconsMapper } from './IconsMapper'
