name: Run E2E tests per DB
description: Run E2E tests per DB

inputs:
  db:
    required: true
    description: db name

runs:
  using: composite
  steps:
    - id: docker-compose-up-per-db
      shell: bash
      run: |
        if [[ ${{ inputs.db }} == "ElasticSearch" ]]; then
          docker-compose deploy/docker-compose/docker-compose.yml up
        fi
