name: Run E2E tests per spans storage DB
description: Run E2E tests per spans storage DB

inputs:
  db:
    required: true
    description: db name

runs:
  using: composite
  steps:
    - id: run-lupa
      shell: bash
      run: |
        echo  ${{ inputs.db }}
        docker-compose -f ${{ fromJson('{ "ElasticSearch": "deploy/docker-compose/docker-compose.yml"}')[ ${{ inputs.db }} ] }} up -d
        # if [[ ${{ inputs.db }} == "ElasticSearch" ]]; then
        #   docker-compose -f deploy/docker-compose/docker-compose.yml up -d
        # fi
