name: Run E2E tests per spans storage DB
description: Run E2E tests per spans storage DB

inputs:
  db:
    required: true
    description: db name

runs:
  using: composite
  steps:
    - id: run-lupa
      shell: bash
      run: |
        export DOCKER_COMPOSE_PATH=\
        $(echo '{ "ElasticSearch": "deploy/docker-compose/docker-compose.yml" }' | jq -r 'to_entries[] | select(.key=="${{ inputs.db }}") | .value')
        echo $DOCKER_COMPOSE_PATH
        docker-compose -f $DOCKER_COMPOSE_PATH up -d

        # docker-compose -f ${{ steps.vars.outputs.docker_compose_path }} up -d
        # echo ::set-output name=docker_compose_path::\
