name: Run E2E tests per spans storage DB
description: Run E2E tests per spans storage DB

inputs:
  spans_storage_db_type:
    required: true
    description: spans storage DB type

runs:
  using: composite
  steps:
    - id: run-teletrace
      shell: bash
      run: |
        export DOCKER_COMPOSE_PATH=\
        $(echo '{ "ElasticSearch": "deploy/docker-compose/docker-compose.e2e.yml" }' | jq -r 'to_entries[] | select(.key=="${{ inputs.spans_storage_db_type }}") | .value')
        docker-compose -f $DOCKER_COMPOSE_PATH up -d
