version: "3.9"
services:
  lupa-collector:
    build:
      dockerfile: ./cmd/all-in-one/Dockerfile
      context: ../
    command: ["--config=/etc/lupa-collector-config.yaml"]
    environment:
      - ES_ENDPOINT=http://elasticsearch:9200
    volumes:
      - ./lupa-collector-config.yaml:/etc/lupa-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy

  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "4320:4320" # OTLP gRPC receiver
    depends_on:
      - lupa-collector

  demo-client:
    build:
      dockerfile: Dockerfile
      context: ./client
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4320
      - DEMO_SERVER_ENDPOINT=http://demo-server:7080/hello
    depends_on:
      - demo-server

  demo-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4320
    ports:
      - "7080"
    depends_on:
      - otel-collector

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  elasticsearch:
    image: elasticsearch:8.4.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 3s
      timeout: 10s
      retries: 50

  kibana:
    image: kibana:8.4.2
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local
