receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4320"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  otlp/2:
    endpoint: lupa-collector:4317
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/2]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
