site_name: Teletrace

theme:
  homepage: https://epsagon.github.io/lupa/
  font:
    text: Roboto

  theme:
  features:
    - navigation.sections
    - content.code.annotate

  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/epsagon/lupa
      name: Teletrace on GithHub
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages

repo_name: epsagon/lupa
repo_url: https://github.com/epsagon/lupa
nav:
  - Overview: index.md
  - understand_the_basics.md
  - Getting Started:
      - Quick Start: getting-started/index.md
      - Deployment:
          - Docker Compose: getting-started/deployment/docker_compose.md
          - Helm Chart: getting-started/deployment/helm_chart.md
      - Sending Data:
          - Introduction: getting-started/sending-data/introduction.md
          - Open Telemetry Collector: getting-started/sending-data/open_telemetry_collector.md
          - Open Telemetry SDK:
              - Java: getting-started/sending-data/open-telemetry-sdk/java.md
              - Python: getting-started/sending-data/open-telemetry-sdk/python.md
              - Javascript: getting-started/sending-data/open-telemetry-sdk/javascript.md
  - Community:
      - Contributing: contributing.md
      - Support: support.md
