site_name: Lupa

theme:
  homepage: https://epsagon.github.io/oss-tracing/
  font:
    text: Roboto

  theme:
  features:
    - navigation.sections
    - content.code.annotate

  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/epsagon/lupa
      name: Lupa on GithHub
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages

repo_name: epsagon/lupa
repo_url: https://github.com/epsagon/lupa
