site_name: Teletrace
repo_name: teletrace/teletrace
repo_url: https://github.com/teletrace/teletrace

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  homepage: https://docs.teletrace.io/
  logo: assets/teletrace_logo_white.svg
  favicon: assets/teletrace_logo.svg

  font:
    text: Roboto

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

  features:
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.footer
    - content.code.annotate
    - content.code.copy
    - content.action.edit

  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/teletrace/teletrace
      name: Teletrace on GithHub

    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/teletrace/shared_invite/zt-1qv0kogcn-KlbBB2yS~gUCGszZoSpJfQ
      name: Teletrace's Slack Workspace

    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/teletrace/teletrace
      name: Teletrace Docker Image

  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  analytics:
    provider: google
    property: G-C9YG1K3ZP1
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            opening an <a href="https://github.com/teletrace/teletrace/issues/new/?title=[Docs Feedback]+{title}+-+{url}" target="_blank" rel="noopener">issue</a>.

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: { alternate_style: true }
  - pymdownx.highlight: { anchor_linenums: true }
  - toc:
      title: On this page
      permalink: true

plugins:
  - search
  - awesome-pages
  - open-in-new-tab

nav:
  - index.md
  - features.md
  - Concepts:
      - concepts/intro.md
      - concepts/distributed-tracing.md
      - concepts/instrumentation.md
      - concepts/glossary.md
  - Operator Guide:
      - operator-guide/architecture-overview.md
      - Deployment:
          - operator-guide/deployment/docker.md
          - operator-guide/deployment/kubernetes.md
  - User Guide:
      - user-guide/application-overview.md
      - Instrumenting Applications:
          - Node.js:
              - user-guide/instrumenting/node/general.md
              - user-guide/instrumenting/node/express.md
          - Python:
              - user-guide/instrumenting/python/general.md
              - user-guide/instrumenting/python/flask.md
              - user-guide/instrumenting/python/fastapi.md
              - user-guide/instrumenting/python/django.md
          - Java:
              - user-guide/instrumenting/java/general.md
              - user-guide/instrumenting/java/spring-boot.md
          - Go:
              - user-guide/instrumenting/go/general.md
              - user-guide/instrumenting/go/gin.md
              - user-guide/instrumenting/go/echo.md
              - user-guide/instrumenting/go/gorilla-mux.md
  - Community:
      - community/contribution.md
      - community/faq.md
      - community/support.md
      - Releases ⧉: https://github.com/teletrace/teletrace/releases
