site_name: OSS tracing

theme:
  logo: assets/ursa-logo-white.png
  homepage: https://epsagon.github.io/oss-tracing-docs/
  font:
    text: Roboto Mono
  
  theme:
  features:
    - navigation.tabs

  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: teal
      toggle:         
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    
copyright: <a href="https://www.flaticon.com/free-icons/ursa-minor" title="ursa minor icons">Ursa minor icons created by Freepik - Flaticon</a>
extra:
  generator: true
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/epsagon/oss-tracing
      name: OSS tracing on github

repo_name: epsagon/oss-tracing
repo_url: https://github.com/epsagon/oss-tracing
