version: "3"

tasks:
  setup-mkdocs-arm64:
    cmds:
      - docker pull ghcr.io/afritzler/mkdocs-material

  serve:
    cmds:
      - docker run --rm -it -p 8000:8000 -v ${PWD}:/docs ghcr.io/afritzler/mkdocs-material
  