version: "3"
services:
  lupa-api:
    expose:
      - "4317"
      - "4318"
    ports:
      - "8080:8080"
    command: ["--config=/etc/lupa-collector-config.yaml"]
    volumes:
      - ./lupa-otel-collector.yaml:/etc/lupa-collector-config.yaml
    environment:
      - ES_ENDPOINT=http://elasticsearch:9200
    build:
      dockerfile: cmd/all-in-one/Dockerfile
      context: ../../
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8080/v1/ping"]
      interval: 60s
      timeout: 5s
      retries: 3
    networks:
      - lupa
    depends_on:
      elasticsearch:
        condition: service_healthy

  demo-client:
    build:
      dockerfile: Dockerfile
      context: ../demo/client
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4320
      - DEMO_SERVER_ENDPOINT=http://demo-server:7080/hello
    depends_on:
      - demo-server
    networks:
      - lupa

  demo-server:
    build:
      dockerfile: Dockerfile
      context: ../demo/server
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4320
    ports:
      - "7080"
    depends_on:
      - otel-collector
    networks:
      - lupa

  otel-collector:
    image: otel/opentelemetry-collector:${OTEL_COLLECTOR_VERSION}
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4320:4320" # OTLP gRPC receiver
    depends_on:
      lupa-api:
        condition: service_healthy
    networks:
      - lupa

  elasticsearch:
    image: elasticsearch:8.4.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      - lupa
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 3s
      timeout: 10s
      retries: 50

  kibana:
    image: kibana:8.4.2
    ports:
      - "5601:5601"
    networks:
      - lupa
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  es_data:
    driver: local
networks:
  lupa:
    internal: false
