version: "3"
services:
  lupa-api:
    image: ""
    build:
      dockerfile: cmd/all-in-one/Dockerfile
      context: ../../

  kibana:
    image: kibana:8.4.2
    ports:
      - "5601:5601"
    networks:
      - lupa
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  es_data:
    driver: local
networks:
  lupa:
    internal: false
