version: "3"
services:
  demo-client:
    build:
      dockerfile: Dockerfile
      context: ../demo/client
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - DEMO_SERVER_ENDPOINT=http://demo-server:7080/hello
    depends_on:
      - demo-server
    networks:
      - lupa

  demo-server:
    build:
      dockerfile: Dockerfile
      context: ../demo/server
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    ports:
      - "7080"
    depends_on:
      - otel-collector
    networks:
      - lupa
