exporters:
  otlp/2:
    endpoint: lupa-api:4317
    tls:
      insecure: true

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4320"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/2]
