receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  elasticsearch:
    endpoints: ["http://elasticsearch:9200/"]

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
