name: Change issue status on assign
on: 
  issues:
    types: 
      - assigned

jobs:
  move-assigned-issue-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        
      - uses: ./.github/change-issue-status
        with:
          target-status: "In progress"
          github-token: ${{ secrets.CUSTOM_AUTOMATION_TOKEN }}
          organization: ${{ secrets.ORGANIZATION_NAME }}
          project-number: ${{ secrets.OSS_PROJECT_NUMBER }}
