name: Deploy Storybook

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: storybook

    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - run: yarn
        working-directory: web

      - run: yarn build-storybook
        working-directory: web

      - run: aws s3 sync ./storybook-static s3://lupa-storybook
        working-directory: web
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"
