name: E2E Tests
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Playwright tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./tests/e2e/playwright
        run: npm install
      - name: Install Playwright Browsers
        working-directory: ./tests/e2e/playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        # uses: ./.github/actions/run-tests
        # id: run-tests-per-db
        # with:
        #   db: ${{ matrix.db }}
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

    # strategy:
    #   matrix:
    #     db: [ElasticSearch]
    # timeout-minutes: 60
    # if: ${{ !startsWith(github.head_ref, 'mergify/') }}
