name: golangci-lint

on:
  pull_request:
    branches:
    - main

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48
          only-new-issues: true
