name: Publish Image
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: "publish-image"
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GH_DOCKER_USERNAME }}
          password: ${{ secrets.GH_DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "{{defaultContext}}:cmd/all-in-one"
          tags: epsagon/lupa:demo
