name: E2E Tests
on:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    # if: ${{ startsWith(github.head_ref, 'mergify/') }}
    name: Run E2E tests
    runs-on: ubuntu-latest
    needs: [wait-pr-ci]
    strategy:
      matrix:
        spans_storage_db_type: [ElasticSearch]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./tests/e2e/playwright
        run: npm install
      - name: Install apt dependencies
        # this step is required in order to successfully install the
        # playwright browsers. For more information, see here:
        # https://github.com/actions/runner-images/issues/675#issuecomment-610483420
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get -o Acquire::Retries=30 update -q
      - name: Install Playwright Browsers
        working-directory: ./tests/e2e/playwright
        run: npx playwright install --with-deps
      - name: Run Teletrace
        uses: ./.github/run-end-to-end-tests
        id: run-teletrace
        with:
          spans_storage_db_type: ${{ matrix.spans_storage_db_type }}
      - name: Run Playwright tests
        working-directory: ./tests/e2e/playwright
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./tests/e2e/playwright/playwright-report/
          retention-days: 30

  wait-pr-ci:
    name: Wait PR CI
    if: ${{ startsWith(github.head_ref, 'mergify/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait PR CI to finish
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: "Wait PR CI"
          check-regexp: ^Lint$|^Golang Lint$|^Validate (PR Title|License Header|pre-commit hooks)$|^Golang Unit Tests.*$

  wait-e2e-tests:
    name: Wait E2E Tests
    if: ${{ startsWith(github.head_ref, 'mergify/') }}
    runs-on: ubuntu-latest
    needs: [wait-pr-ci]
    steps:
      - name: Wait E2E Tests
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: "Wait E2E Tests"
          check-regexp: ^Run E2E tests.*$
