name: Lint PR

on:
  pull_request:
    branches:
      - main

jobs:
  pr-title:
    name: Validate PR Title
    if: ${{ !startsWith(github.head_ref, 'mergify/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@master
      - uses: ./
        with:
          check_filenames: true
          skip: "*.sum,*.sum,*.lock"
          ignore_words_file: ignore-spelling-words.txt
