name: Frontend CI

on:
  merge_group:
  pull_request:
    branches:
      - main
      - merge-queue-test

permissions:
  contents: read
  pull-requests: read

jobs:
  eslint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: lint
        run: make frontend-lint
